#!/usr/bin/env python3
"""Resolve every concept's AST selectors into real line ranges.

Writes `visualizer/src/data/generated/anchors.json`. The visualizer never
resolves a selector itself — that would mean shipping a Python parser to the
browser, and it would mean the anchors could differ between what CI validated
and what the site shows. One resolver, run at build time, committed to the repo,
checked by CI.

Run via `make validate` (which also runs `tools/validate_concepts.py`).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tools import selectors  # noqa: E402
from tools.concepts import load_all  # noqa: E402

OUTPUT = REPO_ROOT / "visualizer" / "src" / "data" / "generated" / "anchors.json"


def build(root: Path = REPO_ROOT) -> dict[str, Any]:
    concepts = load_all(root)
    sources: dict[str, dict[str, Any]] = {}
    failures: list[str] = []
    resolved: dict[str, dict[str, Any]] = {}

    for concept in concepts:
        front = concept.frontmatter
        concept_id = str(front["id"])
        for language, anchor in (front.get("anchors") or {}).items():
            selector = str(anchor["selector"])
            # An `offset:` may be written inside the selector or as a sibling key.
            extra = anchor.get("offset")
            if extra:
                selector = f"{selector} offset:[{int(extra[0])}, {int(extra[1])}]"

            try:
                path = selectors.source_for_language(language, root)
                if not path.is_file():
                    raise selectors.SelectorUnresolvedError(
                        f"no source file for language {language!r}"
                    )
                if language not in sources:
                    text = path.read_text(encoding="utf-8")
                    sources[language] = {
                        "path": str(path.relative_to(root)),
                        "lines": len(text.split("\n")),
                        "bytes": len(text.encode("utf-8")),
                    }
                span = selectors.resolve(language, selector, root)
            except selectors.SelectorError as exc:
                failures.append(f"{concept_id} [{language}] {selector}: {exc}")
                continue

            resolved.setdefault(concept_id, {})[language] = {
                **span.as_dict(),
                "selector": selector,
            }

    document: dict[str, Any] = {
        "$comment": (
            "GENERATED by tools/gen_anchors.py -- do not edit. Concepts declare "
            "AST selectors in content/concepts/*.md; this file is the resolved "
            "line ranges those selectors point at right now. If this file is "
            "stale, run `make validate`."
        ),
        "generator": "tools/gen_anchors.py",
        "sources": dict(sorted(sources.items())),
        "languages": list(selectors.TRACK_LANGUAGES),
        "concepts": dict(sorted(resolved.items())),
    }
    return {"document": document, "failures": failures, "concept_count": len(concepts)}


def main() -> int:
    result = build()
    failures: list[str] = result["failures"]

    for language, info in result["document"]["sources"].items():
        print(f"  source {language:<12} {info['lines']:>5} lines  {info['path']}")

    if failures:
        print(f"\n{len(failures)} anchor(s) failed to resolve:\n", file=sys.stderr)
        for failure in failures:
            print(f"  ! {failure}", file=sys.stderr)
        print(
            "\nEvery selector must resolve in every language the concept "
            "declares. Either the selector is wrong, or the language's source "
            "no longer contains the thing the concept is about -- in which case "
            "the concept's anchor needs updating, not the source.",
            file=sys.stderr,
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(result["document"], indent=2, sort_keys=False) + "\n"
    previous = OUTPUT.read_text() if OUTPUT.exists() else None
    if previous == payload:
        print(f"  anchors up to date ({result['concept_count']} concepts)")
        return 0
    OUTPUT.write_text(payload)
    print(
        f"  wrote {OUTPUT.relative_to(REPO_ROOT)} "
        f"({result['concept_count']} concepts, "
        f"{len(result['document']['concepts'])} anchored)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
