#!/usr/bin/env python3
"""Provenance manifest for every vendored or derived file in this repository.

This module is the single source of truth for `docs/PROVENANCE.md` and for the
sha256 check that CI runs. It is deliberately stdlib-only: the whole point of
this repository is that you should not need a package manager to audit it.

Two kinds of entry live here:

`VENDORED`
    A file whose bytes came from somewhere else. Its sha256 is pinned, and
    `make verify-provenance` fails if the bytes move without a deliberate,
    reviewable edit to this file.

`DERIVED`
    A file we produced by adapting someone else's. Its sha256 is recorded for
    the current revision but is *not* an upstream pin -- it is expected to
    change whenever we change the file. Use `derived=True` for those.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class ProvenanceEntry:
    path: str
    origin: str
    url: str
    license: str
    author: str
    note: str
    #: Literal digest. For pinned entries this is the upstream byte sequence and
    #: the check compares against it, so editing the file fails the build. For
    #: derived entries it is the digest of our current revision, refreshed with
    #: `make provenance`; it is recorded, not enforced.
    sha256: str
    derived: bool = False
    license_file: str | None = None
    aliases: tuple[str, ...] = field(default_factory=tuple)

    def actual_sha256(self) -> str | None:
        target = REPO_ROOT / self.path
        if not target.is_file():
            return None
        digest = hashlib.sha256()
        with target.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1 << 20), b""):
                digest.update(chunk)
        return digest.hexdigest()


#: The pinned reference. Byte-for-byte as vendored. CI fails if this moves.
REFERENCE = ProvenanceEntry(
    path="reference/microgpt.py",
        sha256="4e0c321442692d5a2ccf0328c5e472cd7efa27fa2c8a243438e783054f4eb6ae",
    origin="Andrej Karpathy, microgpt.py (199 lines)",
    url="https://gist.github.com/karpathy/8627fe009c40f57531cb18360106ce95",
    license="Unlicensed by author; reproduced with full attribution for teaching",
    author="Andrej Karpathy",
    note=(
        "An earlier revision of the gist, not its current HEAD. The algorithm is "
        "identical; the differences are comments, the `docs =` list comprehension, "
        "the dataset URL, and a trailing carriage return on the progress print. "
        "Do not edit this file -- it is the reference track, the thing learners "
        "read, and the thing the browser runs."
    ),
)


PROVENANCE: tuple[ProvenanceEntry, ...] = (
    REFERENCE,
    ProvenanceEntry(
        path="reference/microgpt-annotated.py",
        sha256="57e51f2ccb8d8655f1cf9de9955f019283a14222d59d9b3b90ca686f58150244",
        origin="Heavily commented fork of microgpt.py",
        url="https://gist.github.com/karpathy/8627fe009c40f57531cb18360106ce95",
        license="Same as upstream: Karpathy's code, our commentary",
        author="Karpathy (code), this repository (comments)",
        note=(
            "A FORK, not the reference. It is a reading aid and is deliberately "
            "excluded from the parity gate. The line numbers differ completely from "
            "microgpt.py, so never anchor a concept to it."
        ),
        derived=True,
    ),
    ProvenanceEntry(
        path="implementations/c/microgpt.c",
        sha256="c3a94f65840d8343dd693196d1fc6c45e2a3d694d3f14b58ed89f3d570406f61",
        origin="C port in the microgpt-c lineage (micro config, parity track)",
        url="https://github.com/vixhal-baraiya/microgpt-c",
        license="MIT",
        author="Vishal (TheVixhal), adapted by this repository",
        note=(
            "MIT, Copyright (c) 2026 Vishal (TheVixhal). Our local revision does "
            "not match any published upstream commit byte-for-byte: it adds Apple "
            "Accelerate/NEON paths and a portable scalar fallback, caps documents at "
            "MAX_DOC_LEN 20, and emits a JSONL trace. Kept separate from "
            "microgpt-scaled.c on purpose -- this is the parity track."
        ),
        derived=True,
        license_file="THIRD_PARTY_LICENSES/microgpt-c-LICENSE",
    ),
    ProvenanceEntry(
        path="implementations/c/microgpt-scaled.c",
        sha256="40944162388b6d4a62aa5675737e7ba16f124f9cf17cf7c4cff73487c2264d16",
        origin="C port in the microgpt-c lineage (scaled config, benchmark track)",
        url="https://github.com/vixhal-baraiya/microgpt-c",
        license="MIT",
        author="Vishal (TheVixhal), adapted by this repository",
        note=(
            "MIT, Copyright (c) 2026 Vishal (TheVixhal). n_embd 256 / n_head 8 / "
            "n_layer 4 / block 256. Reads and writes a 13 MB model.bin checkpoint, "
            "so it is excluded from the parity gate and used only for throughput."
        ),
        derived=True,
        license_file="THIRD_PARTY_LICENSES/microgpt-c-LICENSE",
    ),
    ProvenanceEntry(
        path="data/input.txt",
        sha256="0a30b5557f192f32ab962680889aac5f6fda0f4cecf40a6d0b5694f58ea8cc4d",
        origin="names.txt from karpathy/makemore, commit 988aa59",
        url="https://github.com/karpathy/makemore/blob/988aa59/names.txt",
        license="MIT (makemore)",
        author="Andrej Karpathy",
        note=(
            "32,033 names, byte-identical to upstream including the absence of a "
            "trailing newline. Committed rather than downloaded so that "
            "reference/microgpt.py never reaches the network: its "
            "`os.path.exists('input.txt')` check finds our copy and short-circuits."
        ),
    ),
    ProvenanceEntry(
        path="data/shakespeare.txt",
        sha256="86c4e6aa9db7c042ec79f339dcb96d42b0075e16b8fc2e86bf0ca57e2dc565ed",
        origin="Tiny Shakespeare character-level corpus",
        url="https://github.com/karpathy/char-rnn",
        license="Public domain (Shakespeare, c. 1590s)",
        author="William Shakespeare, via karpathy/char-rnn",
        note=(
            "40,000 lines, ~1.1 MB. Optional alternative dataset. It is not used by "
            "any v1 track; the point of committing it is that the first thing a "
            "learner wants to try is 'train it on real text'."
        ),
    ),
)


def all_entries() -> tuple[ProvenanceEntry, ...]:
    return PROVENANCE


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that every pinned (non-derived) file still matches its sha256",
    )
    args = parser.parse_args(argv)

    if args.check:
        from tools import check_provenance  # noqa: PLC0415

        return check_provenance.run()

    for entry in all_entries():
        print(f"{entry.sha256:<64}  {entry.path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
