#!/usr/bin/env python3
"""Provenance manifest for every vendored or derived file in this repository.

This module is the single source of truth for `docs/PROVENANCE.md` and for the
sha256 check that CI runs. It is deliberately stdlib-only: the whole point of
this repository is that you should not need a package manager to audit it.

Two kinds of entry live here:

`VENDORED`
    A file whose bytes came from somewhere else. Its sha256 is pinned, and
    `make verify-provenance` fails if the bytes move without a deliberate,
    reviewable edit to this file.

`DERIVED`
    A file we produced by adapting someone else's. Its sha256 is recorded for
    the current revision but is *not* an upstream pin -- it is expected to
    change whenever we change the file. Use `derived=True` for those.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class ProvenanceEntry:
    path: str
    origin: str
    url: str
    license: str
    author: str
    note: str
    #: Literal digest. For pinned entries this is the upstream byte sequence and
    #: the check compares against it, so editing the file fails the build. For
    #: derived entries it is the digest of our current revision -- *recorded*,
    #: not enforced -- and it is refreshed by
    #: `python3 -m tools.provenance --refresh-derived`, which re-hashes derived
    #: entries and rewrites this file. Pinned entries are never rewritten by
    #: that command; a pinned file that moved has to be a deliberate,
    #: reviewable edit here.
    sha256: str
    derived: bool = False
    license_file: str | None = None
    aliases: tuple[str, ...] = field(default_factory=tuple)

    def actual_sha256(self) -> str | None:
        target = REPO_ROOT / self.path
        if not target.is_file():
            return None
        digest = hashlib.sha256()
        with target.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1 << 20), b""):
                digest.update(chunk)
        return digest.hexdigest()


#: The pinned reference. Byte-for-byte as vendored. CI fails if this moves.
REFERENCE = ProvenanceEntry(
    path="reference/microgpt.py",
        sha256="4e0c321442692d5a2ccf0328c5e472cd7efa27fa2c8a243438e783054f4eb6ae",
    origin="Andrej Karpathy, microgpt.py (199 lines)",
    url="https://gist.github.com/karpathy/8627fe009c40f57531cb18360106ce95",
    license="Unlicensed by author; reproduced with full attribution for teaching",
    author="Andrej Karpathy",
    note=(
        "An earlier revision of the gist, not its current HEAD. The algorithm is "
        "identical; the differences are comments, the `docs =` list comprehension, "
        "the dataset URL, and a trailing carriage return on the progress print. "
        "Do not edit this file -- it is the reference track, the thing learners "
        "read, and the thing the browser runs."
    ),
)


PROVENANCE: tuple[ProvenanceEntry, ...] = (
    REFERENCE,
    ProvenanceEntry(
        path="implementations/rust/src/lib.rs",
        sha256="4bced112f2db2bf8662082051fa550f82ab793bed251be9398c6f672947a2f15",
        origin="Rust port of microgpt.py (micro config, parity track) -- FROZEN",
        url="https://gist.github.com/karpathy/8627fe009c40f57531cb18360106ce95",
        license="MIT",
        author="Karpathy (algorithm), this repository (port)",
        note=(
            "FROZEN IN PLACE, and the digest above is the mechanism. `derived=True` "
            "is the honest flag -- this is our adaptation of Karpathy's Python, not "
            "bytes fetched from somewhere -- but the check compares the digest either "
            "way, so editing this file fails the build. It is called out here because "
            "'derived' normally means the opposite.\n"
            "The research loop in tools/autoresearch.py measures every candidate "
            "against this file and the site renders it, so 'the first version' is only "
            "a real claim while its bytes cannot move. The tuned copy lives at "
            "autoresearch/candidate/src/lib.rs and is expected to diverge freely; this "
            "one is not. tools/tests/test_autoresearch.py asserts this digest by name.\n"
            "It is also wrong about gradients -- docs/KNOWN-ISSUES.md issue 5, a 6.32% "
            "overestimate found by finite difference -- and that is left in place on "
            "purpose, because it is the thing every candidate is measured against."
        ),
        derived=True,
    ),
    ProvenanceEntry(
        path="implementations/rust/Cargo.toml",
        sha256="0b743d919a98011f7f995db246ebc45f22dafc24233580aab342960cd380aa7b",
        origin="Rust port build manifest -- FROZEN with its crate",
        url="https://gist.github.com/karpathy/8627fe009c40f57531cb18360106ce95",
        license="MIT",
        author="Karpathy (algorithm), this repository (port)",
        note=(
            "Frozen with the crate it belongs to; see the note on lib.rs beside it. "
            "The profile settings are part of what the research loop measures: "
            "debug-assertions and overflow-checks are on in release, deliberately, "
            "because a model that silently wraps a float is worse than one that stops "
            "-- and for the research loop, one that stops is measurable and one that "
            "wraps is not."
        ),
        derived=True,
    ),
    ProvenanceEntry(
        path="implementations/rust/src/main.rs",
        sha256="0160147568e6ac5a1c0448dccefd638931467cdcd1225e47529d078d97fbc324",
        origin="Rust port binary entry point -- FROZEN with its crate",
        url="https://gist.github.com/karpathy/8627fe009c40f57531cb18360106ce95",
        license="MIT",
        author="Karpathy (algorithm), this repository (port)",
        note=(
            "Six lines that call microgpt::run(). Frozen with its crate; see the note "
            "on lib.rs."
        ),
        derived=True,
    ),
    ProvenanceEntry(
        path="reference/microgpt-annotated.py",
        sha256="57e51f2ccb8d8655f1cf9de9955f019283a14222d59d9b3b90ca686f58150244",
        origin="Heavily commented fork of microgpt.py",
        url="https://gist.github.com/karpathy/8627fe009c40f57531cb18360106ce95",
        license="Same as upstream: Karpathy's code, our commentary",
        author="Karpathy (code), this repository (comments)",
        note=(
            "A FORK, not the reference. It is a reading aid and is deliberately "
            "excluded from the parity gate. The line numbers differ completely from "
            "microgpt.py, so never anchor a concept to it."
        ),
        derived=True,
    ),
    ProvenanceEntry(
        path="implementations/c/microgpt.c",
        sha256="1298a20cb9b9698aec2bb6f268d9fddbf1dd1e5341bc63eeedd7fc3875b7a7b9",
        origin="C port in the microgpt-c lineage (micro config, parity track)",
        url="https://github.com/vixhal-baraiya/microgpt-c",
        license="MIT",
        author="Vishal (TheVixhal), adapted by this repository",
        note=(
            "MIT, Copyright (c) 2026 Vishal (TheVixhal). Our local revision does "
            "not match any published upstream commit byte-for-byte: it adds Apple "
            "Accelerate/NEON paths and a portable scalar fallback, caps documents at "
            "MAX_DOC_LEN 20, and emits a JSONL trace. Kept separate from "
            "microgpt-scaled.c on purpose -- this is the parity track."
        ),
        derived=True,
        license_file="THIRD_PARTY_LICENSES/microgpt-c-LICENSE",
    ),
    ProvenanceEntry(
        path="implementations/c/microgpt-scaled.c",
        sha256="6a0260ec072ce31b5f7cebbb369c167c13d5191a24ab4f71e01b90f6488cd744",
        origin="C port in the microgpt-c lineage (scaled config, benchmark track)",
        url="https://github.com/vixhal-baraiya/microgpt-c",
        license="MIT",
        author="Vishal (TheVixhal), adapted by this repository",
        note=(
            "MIT, Copyright (c) 2026 Vishal (TheVixhal). n_embd 256 / n_head 8 / "
            "n_layer 4 / block 256. Reads and writes a 13 MB model.bin checkpoint, "
            "so it is excluded from the parity gate and used only for throughput."
        ),
        derived=True,
        license_file="THIRD_PARTY_LICENSES/microgpt-c-LICENSE",
    ),
    ProvenanceEntry(
        path="data/input.txt",
        sha256="0a30b5557f192f32ab962680889aac5f6fda0f4cecf40a6d0b5694f58ea8cc4d",
        origin="names.txt from karpathy/makemore, commit 988aa59",
        url="https://github.com/karpathy/makemore/blob/988aa59/names.txt",
        license="MIT (makemore)",
        author="Andrej Karpathy",
        note=(
            "32,033 names, byte-identical to upstream including the absence of a "
            "trailing newline. Committed rather than downloaded so that "
            "reference/microgpt.py never reaches the network: its "
            "`os.path.exists('input.txt')` check finds our copy and short-circuits."
        ),
    ),
    ProvenanceEntry(
        path="data/shakespeare.txt",
        sha256="86c4e6aa9db7c042ec79f339dcb96d42b0075e16b8fc2e86bf0ca57e2dc565ed",
        origin="Tiny Shakespeare character-level corpus",
        url="https://github.com/karpathy/char-rnn",
        license="Public domain (Shakespeare, c. 1590s)",
        author="William Shakespeare, via karpathy/char-rnn",
        note=(
            "40,000 lines, ~1.1 MB. Optional alternative dataset. It is not used by "
            "any v1 track; the point of committing it is that the first thing a "
            "learner wants to try is 'train it on real text'."
        ),
    ),
)


def all_entries() -> tuple[ProvenanceEntry, ...]:
    return PROVENANCE


def _rewrite_derived_digests() -> int:
    """Re-hash every `derived=True` entry and write the new digests back to this file.

    The docstring above claims derived digests are "refreshed with `make
    provenance`", and until now there was no code that did it: `make provenance`
    only regenerates `docs/PROVENANCE.md` from the *literal* values declared here,
    so a derived file that changed left the manifest stale and `--check` failing
    until somebody hand-edited a hash. That is how the two C ports ended up
    failing `--check` on a clean checkout of `main`.

    This is a source rewrite rather than a generated sidecar on purpose. The
    manifest is hand-authored -- the notes and the URLs are prose -- so a
    separate digest file would be one more thing to keep in sync with no gain.

    Two deliberate limits:

    * Only `derived` entries move. A pinned entry's digest is the *upstream* byte
      sequence; rewriting it from the local file would turn a tamper alarm into a
      rubber stamp, which is the opposite of what `pinned` is for. If a pinned
      file legitimately needs to change, that is a reviewable edit to this file
      with a reason, done by a person.
    * Pinned entries are re-checked and reported, never rewritten, so a run of
      this on a tree where something vendored was edited says so loudly.
    """
    import re

    source = Path(__file__).read_text(encoding="utf-8")
    changed: list[tuple[str, str, str]] = []
    untouched: list[str] = []
    pinned_moved: list[str] = []

    for entry in all_entries():
        target = REPO_ROOT / entry.path
        if not target.is_file():
            raise SystemExit(f"error: {entry.path} is missing; cannot refresh its digest")
        actual = entry.actual_sha256()
        if actual is None:
            raise SystemExit(f"error: {entry.path} is missing; cannot refresh its digest")
        if actual == entry.sha256:
            continue
        if not entry.derived:
            pinned_moved.append(f"  ! {entry.path}: PINNED and moved")
            continue
        pattern = re.compile(
            r'(path="' + re.escape(entry.path) + r'",\n'
            r'\s*sha256=")[0-9a-f]{64}(")'
        )
        if not pattern.search(source):
            raise SystemExit(
                f"error: could not find the sha256 line for {entry.path} in "
                f"{Path(__file__).name}. The declaration order or formatting "
                f"changed; fix the pattern in _rewrite_derived_digests rather "
                f"than editing the hash by hand."
            )
        source = pattern.sub(rf"\g<1>{actual}\g<2>", source, count=1)
        changed.append((entry.path, entry.sha256, actual))

    for path, old, new in changed:
        print(f"  refreshed {path}\n    {old}\n -> {new}")
    for path in pinned_moved:
        print(path)
    if not changed and not pinned_moved:
        print("  every derived digest already current")

    if changed:
        Path(__file__).write_text(source, encoding="utf-8")
        print(f"\n  updated {Path(__file__).name}; now run `make provenance` to "
              f"regenerate docs/PROVENANCE.md from it")

    if pinned_moved:
        print(
            "\nerror: a PINNED file changed. Pinned digests are the upstream bytes "
            "and are never rewritten by this command -- if the change is "
            "intentional, update that entry's sha256 and note by hand why."
        )
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that every pinned (non-derived) file still matches its sha256",
    )
    parser.add_argument(
        "--refresh-derived",
        action="store_true",
        help="re-hash every derived=True entry and write the digests back to this "
        "file, then report (but never rewrite) any pinned entry that moved",
    )
    args = parser.parse_args(argv)

    if args.refresh_derived:
        return _rewrite_derived_digests()

    if args.check:
        from tools import check_provenance  # noqa: PLC0415

        return check_provenance.run()

    for entry in all_entries():
        print(f"{entry.sha256:<64}  {entry.path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
