#!/usr/bin/env python3
"""Render `content/` into typed JSON for the app.

Emits `visualizer/src/data/generated/content.json` and `index.json`:

- **content.json** — one entry per concept: frontmatter, and the body already
  split into typed blocks (prose / callout / shape / term / trace / lang).
- **index.json** — chapters in order, the graph edges derived from `prereqs`, and
  the glossary. Everything the router and the graph need, with no parsing at
  runtime.

The directive syntax is documented in `docs/ADDING-A-LANGUAGE.md` and in
`tools/concepts.py`. The short version:

    :::callout "A titled aside"
    ...body...

    :::term rmsnorm

    :::shape q_h

    :::trace attn step=0 pos=3 head=0

    :::lang c
    ...closed by the next :::lang or the end of the body...

Run via `make validate` (which runs `gen_anchors.py` then this) or
`python3 -m tools.render_content`.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tools.concepts import Concept, load_all, load_index  # noqa: E402

OUT_DIR = REPO_ROOT / "visualizer" / "src" / "data" / "generated"
CONTENT_OUT = OUT_DIR / "content.json"
INDEX_OUT = OUT_DIR / "index.json"

#: Keys copied straight through from frontmatter. Anything not listed is dropped,
#: so a typo in a concept's frontmatter cannot quietly become an undefined field
#: in the shipped JSON.
FRONTMATTER_KEYS = (
    "id",
    "title",
    "chapter",
    "order",
    "summary",
    "difficulty",
    "math",
    "shapes",
    "related",
    "prereqs",
    "traces",
)

GENERATED_HEADER = (
    "GENERATED by tools/render_content.py from content/ -- do not edit. "
    "Run `make validate` to regenerate."
)


def render_block(block: Any) -> dict[str, Any]:
    """One body block -> one JSON object the app can switch on."""
    if block.kind == "prose":
        return {"kind": "prose", "markdown": block.text}

    out: dict[str, Any] = {"kind": block.name, "line": block.line_no}
    if block.args:
        out["args"] = block.args
    if block.quoted:
        out["title"] = block.quoted
    if block.text:
        out["markdown"] = block.text
    if block.name == "term":
        # The term name is the body of a one-line inline directive.
        out["term"] = block.text.strip() or block.quoted.strip()
    return out


def render_concept(concept: Concept) -> dict[str, Any]:
    front = {key: concept.frontmatter[key] for key in FRONTMATTER_KEYS if key in concept.frontmatter}
    return {
        **front,
        "anchors": concept.frontmatter.get("anchors", {}),
        "blocks": [render_block(block) for block in concept.blocks],
    }


def build_index_payload(concepts: list[Concept], index: dict[str, Any]) -> dict[str, Any]:
    by_id = {c.id: c for c in concepts}
    chapters = []
    for chapter in index["chapters"]:
        members = [c for c in chapter["concepts"] if c in by_id]
        chapters.append(
            {
                "id": chapter["id"],
                "order": chapter["order"],
                "title": chapter["title"],
                "blurb": chapter.get("blurb", ""),
                "concepts": [
                    {
                        "id": m,
                        "title": by_id[m].title,
                        "summary": by_id[m].frontmatter.get("summary", ""),
                        "order": by_id[m].frontmatter.get("order", 0),
                        "difficulty": by_id[m].frontmatter.get("difficulty", 2),
                    }
                    for m in members
                ],
            }
        )

    # Graph edges, derived from `prereqs` rather than declared a second time in
    # index.json. One source of truth: the concept files.
    edges = []
    for concept in concepts:
        for parent in concept.frontmatter.get("prereqs", []) or []:
            edges.append({"from": parent, "to": concept.id})
    for concept in concepts:
        for other in concept.frontmatter.get("related", []) or []:
            edges.append({"from": concept.id, "to": other, "kind": "related"})

    return {
        "$comment": GENERATED_HEADER,
        "reference": index["reference"],
        "hyperparameters": index["hyperparameters"],
        "chapters": chapters,
        "edges": edges,
        "glossary": index.get("glossary", {}).get("terms", {}),
    }


def main() -> int:
    concepts = load_all(REPO_ROOT)
    index = load_index(REPO_ROOT)

    payload = {
        "$comment": GENERATED_HEADER,
        "concepts": [render_concept(c) for c in sorted(concepts, key=lambda c: c.id)],
    }
    index_payload = build_index_payload(concepts, index)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for path, data in ((CONTENT_OUT, payload), (INDEX_OUT, index_payload)):
        text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            written.append(path.relative_to(REPO_ROOT))
        else:
            written.append(f"{path.relative_to(REPO_ROOT)} (unchanged)")

    blocks = sum(len(c["blocks"]) for c in payload["concepts"])
    for entry in written:
        print(f"  {entry}")
    print(
        f"rendered {len(payload['concepts'])} concepts, {blocks} blocks, "
        f"{len(index_payload['chapters'])} chapters, {len(index_payload['edges'])} edges"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
